server:
  port: 8888

# example values
indexing-settings:
  sites:
    - url: https://dombulgakova.ru/
      name: Home of Bulgakov
      id: 1
    - url: https://www.svetlovka.ru/
      name: Светловка
      id: 2
    - url: https://et-cetera.ru/mobile/
      name: Et-cetera mobile
      id: 3
    - url: https://nikoartgallery.com/
      name: Gallery Art of Niko
      id: 4
    - url: https://nopaper.ru/
      вname: NoPaper
      id: 5
    - url: https://www.lutherancathedral.ru/
      name: Luteran Cathedral
      id: 6



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&serverTimezone=UTC
    username: root
    password: a89Lx7z1234!
    spring:
      jpa:

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true





